export const FETCH_EMAIL_REQUEST = "FETCH_EMAIL_REQUEST";
export const FETCH_EMAIL_SUCCESS = "FETCH_EMAIL_SUCCESS";
export const FETCH_EMAIL_FAIL = " FETCH_EMAIL_FAIL";
export const SET_EMAIL = "SET_EMAIL";
export const SET_PASSWORD = "SET_PASSWORD";
